### ISSUE TITLE
Physics lab 2 ->Bugs -> Medium-

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#110]

**Comment by MariyaPa** [comment]
First of all you forgot to include one of the commands:
/1120001-ad_time.r1
but it's good you've implemented it.
Then, you slightly messed up the textures - look at line 26, D34, D36. The texture from line 26 doesn't appear at all.
Now, I had the same NPC for C12 and C13 to ask questions, NPCs are supposed to be different NPCs. And also the same prob. for C21 and C23.
Finally, NPCs are supposed to stop asking their question when either positive or negative feedback is there. But it didn't happen in I 24.
https://docs.google.com/spreadsheets/d/1Ofn3p-uEhqk8zdav7JZKvHBxTnZr7ChvJUcdWxI4WJI/edit#gid=2076443570
Other than that I have moved some of NPC to the second row - it's better and the boards (as I expect a simulator and a whiteboard at the front)

**Comment by raynaglieri** [comment]
So the issues dealing with wrong textures and incorrect NPCs asking questions has been fixed. They were simple offset errors in the command script.  However, for last issue: the the current  NPC template is designed to handle questions in a _**question:response**_ format. For this scenario, I simply made the response empty. Technically its still there and is required input.  When I coded this scenario, I assumed that the trainee would respond before the facilitator inputs feedback.  So, unless the NPC is pulled out of its response state, it will keep asking the question until someone responds. This is why _-ad_negative_ and its feedback commands don't have the same issue. Here, the feedback commands force the NPC out of its response state, so it can say something new.  So the meat of the issue is, without serious modification to our existing model, the command script can't tell when the trainee responds and therefore doesn't know whether or not the NPC needs to be forced out of its response state. If I always assume that the trainee never responds, you may see the  annoying error message: _"Unknown command in state control channel."_.  This is because there is a good chance the trainee did say something and the NPC has already returned to idle. I could remove the error message but the template file would have to be modified. That would be a sloppy solution but may ultimately be necessary. The other solution  is that we circumvent the  NPC ask action and simply make it  regular action where the NPC raises their hand and asks the question simultaneously. There would be no "Excuse me" or calling on NPC's names. Let me know how I should proceed.

**Comment by MariyaPa** [comment]
Ok, I think it should be fine as is now. I just need to include in facil protocol that all the interactions still require some keyword before facil pushes a feedback or the next command.

**Comment by raynaglieri** [comment]
Unless the document states it, no keyword is required for most interactions. Also according to the design document, the trainee is supposed to respond before a reaction is given. Although I'm assuming now the trainee isn't using text chat.  What I can do is send an empty action command to force the NPC out of the reaction state. Doing this would avoid the error message since the NPC won't be going from idle to idle. Let me see if I can think of a cleaner solution, then I'll get back to you ASAP

**Comment by MariyaPa** [comment]
Ok, so let me know when you finish with an empty action command so that I could proceed with testing.

**Comment by raynaglieri** [comment]
Okay, I just updated the scripts. All issues should be resolved now.
