### ISSUE TITLE
Physics Lab ->Bugs ->Urgent

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#25]
Thank you for redoing so much in the Lab, but there are some things you missed: 1) pop-up and part of the scenario in G47; textures for D23 and D25. I have also added different textures for different groups at the beginning - D13.
2) Gender of the NPCs
3) Audio - I'm not sure I have heard any.

https://docs.google.com/spreadsheets/d/1Zd2V-rm_jh7gpLCumZ6IJNWK82nxHQLqnPiPB1645Mo/edit#gid=2076443570

**Comment by raynaglieri** [comment]
1. I've fixed the slides D23, D25(design doc is not aligned correctly). I will not be able to implement the added D13 functionality by 3/2. For G47, I forgot to include the commands in my last comment:
-d_noextratime
-d_extratime
2.Fixed. 
3. Audio is disabled since we do not have the updated audio files for brief non-content specific responses.

**Comment by MariyaPa** [comment]
Thank you, Ray. Could you try D13 ASAP? It looks like we have a first tester tomorrow.

**Comment by raynaglieri** [comment]
Already done. The NPCs should also have audio.
