### ISSUE TITLE
Lecture rooms (teaching adaptively and explaining) -> Enhancement -> Urgent (before thursday, the 12th))

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#49]
Add NPCs reactions when their comment is addressed. "Yes, gotcha." "Allright." "Ok. Nice" "Yes, fine."
You could possibly attach it to the next facil. command before the next NPC's question.

If teaching adaptively can be done before thursday - it would be great!

**Comment by raynaglieri** [comment]
Sorry for the delay, I had to rework the script a little, since this scenario was not set up to handle NPC feedback.  To fix this, I  added a function to the NPC's called "FollowUp". This allows the Facilitator to enter a command that tells recently active NPCs to provide feedback. I'll explain it more at the meeting. I still need to implement this for the explaining lecture.

**Comment by raynaglieri** [comment]
I've tested pushed the update for teaching adaptively lecture, still working on the explaining  lecture. I'll close the issue when I've completed both.
