### ISSUE TITLE
Teach adaptive 3 -> Bugs -> Medium-High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#95]
Hi, Ray,

make sure you have implemented the red text in G20.

https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=1241447716

**Comment by MariyaPa** [comment]
First pop-up - yes, and then NPCs interactions. But not the second pop-up. I tried now. And it still didn't show.

**Comment by raynaglieri** [comment]
I've tested on both test user and facil 2 accounts and I can;t replicate the bug. It could be a viewer issue, so I've added a 1 second offset between the NPC interaction and the pop-up.  Sometimes if commands are called too close together, the script can ignore a command. See if it works for you now. If not, you'll have to show me what you are seeing since I can't duplicate it.

**Comment by MariyaPa** [comment]
Well, Zhaihuan did the testing yesterday with one of the new PhD students and also had the same problem. Maybe try to re-arrange it as a part of feedback? Or a new command line?

**Comment by raynaglieri** [comment]
Was this recorded? I've hand tested the whole scenario multiple times now; I've had no luck duplicating the issue.  Regardless, I've made it a separate command: _-ad_confid!_ .  Let me know if that works.  Also check to make sure you are running the latest version of Firestorm.
